apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-workflow
  annotations:
    github.com/project-slug: marublaize/test-workflow
spec:
  type: other
  lifecycle: unknown
  owner: marublaize
